name: Blog Post Workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.4.2
        with:
          max_post_count: "4"
          feed_list: "https://dev.to/feed/hemang2001,https://twitter.com/HemangBairwa/feed,https://hemangbairwa.me/blog/atom.xml"
